#!/bin/bash
# shellcheck disable=SC2120

set -euo pipefail

########################################################################
#
# To add a command, add a function below and then add an entry for it
# (optionally w/ a shortcut version) to the case statement at the end.
#
# Be sure to run shellcheck on this file.
#
########################################################################

each() { local IFS=; while read -r -d '' it; do $1 "$it"; done ; }
q() { find "$1" "${@:2}" -print0 ; }

########################################################################

OUT="${OUT:=_public}"

########################################################################

src-dirs()  { q src -mindepth 1 -type d "$@" ;}
src-files() { q src -type f ! -name '_*' "$@" ;}
src-blog()  { q src/blog -type f ! -name '_*' -name '*.md' "$@" ;}

make-dir() { mkdir -p ".tmp/${1#src/}" ;}
copy-src() { cp "$1" ".tmp/${1#src/}" ;}

hoot() {
  out=${1/.hoot/}
  PWD=src ./lib/hoot/hoot "${1#src/}" \
    > ".tmp/${out#src/}"
}

blog-post() {
  file=${1#src/}
  out=${file/.hoot.md/}
  # shellcheck disable=SC2002
  cat "$1" \
    | awk '/---/ && !x { gsub(/---+/, "$[+ block content +]"); x=1}; 1' - \
    | echo -e "$(cat -)\n\n\$[- content -]\n\$[> ~/blog/_base.hoot.html]" \
    | PWD=src FILE="${file}" ./lib/hoot/hoot - \
    > ".tmp/${out}.html"
}

########################################################################

cmd-dbg() {
  blog-post src/src/blog/libui/index.hoot.md
}

cmd-init() {
  git submodule update --init
  make lib/hoot/hoot
  make lib/lowdown/lowdown
}

cmd-build() {
  printf 'Building... '

  rm -rf .tmp; mkdir .tmp

  src-dirs | each make-dir
  src-files ! -name '*.hoot.md' -name '*.hoot.*' | each hoot 
  src-files ! -name '*.hoot.*' | each copy-src
  src-blog -name '*.hoot.md' | each blog-post

  cp -R static/* .tmp

  rm -rf "$OUT"
  mv -f .tmp "$OUT"

  echo "Done"
}

cmd-watch() {
  set +e
  while true; do
    find src static -type f \
      | entr -d ./asdf _BUILD

    # This ensures that if we kill entr with ctrl-c,
    # we break out of the loop. Otherwise, it is very
    # difficult to kill this watch function.
    # shellcheck disable=SC2181
    if [ $? -eq 0 ]; then exit 0; fi
  done
}

cmd-post() {
  path="src/blog/$1"
  mkdir -p "$path"
  touch "$path/index.hoot.md"
  vim "$path/index.hoot.md"
}

########################################################################

cmd=${1:-h}

case "$cmd" in
  "d" | "_DEBUG") cmd-dbg ;;
  "B" | "_BUILD") cmd-build ;;
  "i" | "init")   cmd-init ;;
  "b" | "build")  cmd-init && cmd-build ;;
  "w" | "watch")  cmd-init && cmd-watch ;;
  "p" | "post")   cmd-post "${@:2}" ;;
  *)
    echo "Commands:"
    echo "    i, init   Set up the repository"
    echo "    b, build  Build the website"
    echo "    w, watch  Watch for changes and rebuild"
    echo "    p, post   Create a new blog post"
  ;;
esac



########################################################################
# vim: set tw=72 fdm=marker sts=2 ts=2 sw=2 et :
########################################################################
